### ISSUE TITLE
没有实现rsa2加密算法吗？

### ISSUE THREAD

**Issue by lianchengtong** [yuchenfw/gocrypt#2]
rsa2算法好了没有实现哦，现在都不用rsa,直接用rsa2啦

**Comment by yuchenfw** [comment]
RSA2实际上是SHA256WithRSA，加密时sha指定为SHA256即可

**Comment by lianchengtong** [comment]
你这个在加密方法里哪指定？
func (rc *rsaCrypt) Encrypt(src string, outputDataType gocrypt.Encode) (dst string, err error) {
	secretInfo := rc.secretInfo
	if secretInfo.PublicKey == "" {
		return "", fmt.Errorf("secretInfo PublicKey can't be empty")
	}
	pubKeyDecoded, err := gocrypt.DecodeString(secretInfo.PublicKey, secretInfo.PublicKeyDataType)
	if err != nil {
		return
	}
	pubKey, err := x509.ParsePKIXPublicKey(pubKeyDecoded)
	if err != nil {
		return
	}
	var dataEncrypted []byte
	dataEncrypted, err = rsa.EncryptPKCS1v15(rand.Reader, pubKey.(*rsa.PublicKey), []byte(src))
	if err != nil {
		return
	}
	return gocrypt.EncodeToString(dataEncrypted, outputDataType)
}

**Comment by yuchenfw** [comment]
type RSASecret struct {
	PublicKey          string
	PublicKeyDataType  gocrypt.Encode
	PrivateKey         string
	PrivateKeyDataType gocrypt.Encode
	PrivateKeyType     gocrypt.Secret
}
secretInfo:=RSASecret{}
handle := NewRSACrypt(secretInfo)
在secretInfo里指定
